version: "3"

services:
  _: &default
    image: ""
    profiles: [ dockerized ]
    stop_grace_period: 1s
    tty: true
    stdin_open: true
  jq:
    <<: *default
    image: stedolan/jq
  node: &node
    <<: *default
    image: "node:${NODE_VERSION}"
    entrypoint: [ "node" ]
    volumes:
      - "node_modules:/usr/local/lib/node_modules"
      - "npm:/root/.npm"
  npm:
    <<: *node
    entrypoint: [ "npm" ]
  npx:
    <<: *node
    entrypoint: [ "npx" ]
  protoc:
    <<: *default
    image: "protoc:${PROTOC_VERSION}"
    build:
      context: apps/protoc
      args:
        PROTOC_VERSION: "${PROTOC_VERSION}"
        PROTOC_BASE: "${PROTOC_BASE}"
        PROTOC_ARCH: "${PROTOC_ARCH}"
  tsc:
    <<: *node
    entrypoint: [ "npx", "--package=typescript@${TSC_VERSION}", "tsc" ]
  s3cmd:
    <<: *default
    build:
      context: apps/s3cmd
      args:
        S3CMD_VERSION: "${S3CMD_VERSION}"
        S3CMD_BASE: "${S3CMD_BASE}"
    image: "s3cmd:${S3CMD_VERSION}"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-}"
    volumes:
      - "${HOME}:/root"
  swagger-codegen:
    <<: *default
    image: "swaggerapi/swagger-codegen-cli-v3:${SWAGGER_CODEGEN_VERSION}"
  vue:
    <<: *node
    entrypoint: [ "npx", "--package=@vue/cli@${VUE_VERSION}", "vue" ]
  wget:
    <<: *default
    image: "${DEFAULT_BASE}"
    entrypoint: [ "wget" ]
  http:
    <<: *default
    image: "alpine/httpie:${HTTPIE_VERSION}"
    entrypoint: [ "http" ]
volumes:
  node_modules: { }
  npm: { }
