version: "3"

services:
  alpine:
    image: "alpine:latest"
  jq:
    image: stedolan/jq
  node: &node
    image: "node:${NODE_VERSION}"
    entrypoint: [ "node" ]
    volumes:
      - "node_modules:/usr/local/lib/node_modules"
      - "npm:/root/.npm"
  npm:
    <<: *node
    entrypoint: [ "npm" ]
  npx:
    <<: *node
    entrypoint: [ "npx" ]
  protoc:
    image: "protoc:${PROTOC_VERSION}"
    build:
      context: apps/protoc
      args:
        PROTOC_VERSION: "${PROTOC_VERSION}"
        PROTOC_BASE: "${PROTOC_BASE}"
        PROTOC_ARCH: "${PROTOC_ARCH}"
  tsc:
    <<: *node
    entrypoint: [ "npx", "--package=typescript@${TSC_VERSION}", "tsc" ]
  s3cmd:
    build:
      context: apps/s3cmd
      args:
        S3CMD_VERSION: "${S3CMD_VERSION}"
        S3CMD_BASE: "${S3CMD_BASE}"
    image: "s3cmd:${S3CMD_VERSION}"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-}"
    volumes:
      - "${HOME}:/root"
  swagger-codegen:
    image: "swaggerapi/swagger-codegen-cli-v3:${SWAGGER_CODEGEN_VERSION}"
  vue:
    <<: *node
    entrypoint: [ "npx", "--package=@vue/cli@${VUE_VERSION}", "vue" ]
    stop_grace_period: 0s
volumes:
  node_modules: { }
  npm: { }
